### ISSUE TITLE
Failed to start

### ISSUE THREAD

**Issue by andyjwest** [MicrosoftDocs/powerbi-docs#1983]
I ran into some dependency issues, which seems to happen regardless of env with pbiviz 3.1.10.

Error: Cannot find module '@babel/plugin-proposal-numeric-separator'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.&lt;anonymous&gt; (/usr/local/lib/node_modules/powerbi-visuals-tools/node_modules/@babel/preset-env/lib/available-plugins.js:81:63)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.&lt;anonymous&gt; (/usr/local/lib/node_modules/powerbi-visuals-tools/node_modules/@babel/preset-env/lib/index.js:41:48)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
 @ multi ./.tmp/precompile/visualPlugin.ts visual.js[0]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d42a638-f0b9-abd1-43da-0c1618394948
* Version Independent ID: 1350b334-88ef-1aaf-61b6-6b78ab1baf82
* Content: [Developing a Power BI visual - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/custom-visual-develop-tutorial#prerequisites)
* Content Source: [powerbi-docs/developer/visuals/custom-visual-develop-tutorial.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/visuals/custom-visual-develop-tutorial.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by KesemSharabi** [comment]
Hi @uve, can you please assist with @andyjwest's issue?

**Comment by uve** [comment]
please install an updated version of [powerbi-visuals-tools@3.1.11](https://www.npmjs.com/package/powerbi-visuals-tools)

**Comment by andyjwest** [comment]
updating solved the issue thanks!

**Comment by KesemSharabi** [comment]
Thanks @uve for solving this issue.
