### ISSUE TITLE
Unable to integrate Python with Power BI

### ISSUE THREAD

**Issue by yogesh5c4** [MicrosoftDocs/powerbi-docs#2144]
while running the sample python script in powerbi, I am getting below error :
Details: "ADO.NET: Python script error.
Traceback (most recent call last):
  File "PythonScriptWrapper.PY", line 2, in <module>
    import os, pandas, matplotlib
  File "C:\Users\SasanapY\AppData\Local\Continuum\anaconda3\Anaconda64bit\lib\site-packages\matplotlib\__init__.py", line 205, in <module>
    _check_versions()
  File "C:\Users\SasanapY\AppData\Local\Continuum\anaconda3\Anaconda64bit\lib\site-packages\matplotlib\__init__.py", line 190, in _check_versions
    from . import ft2font
ImportError: DLL load failed: The specified module could not be found.
"

**Comment by maggiesMSFT** [comment]
Hi, @yogesh5c4 -- are you referring to a specific article in the documentation? If so, can you provide a link? It sounds like this may be a support question. You can try asking in the Community forum, https://community.powerbi.com/ or in the support site, https://powerbi.microsoft.com/en-us/support/
thanks!

**Comment by maggiesMSFT** [comment]
Hi, @yogesh5c4 -- haven't heard from you, so I'm closing this issue. Thanks.
