### ISSUE TITLE
Sample code not working properly

### ISSUE THREAD

**Issue by satishrabari** [MicrosoftDocs/powerbi-docs#3126]
Normally, the sample code is working fine, but I get the following error when I try to open reports in multiple tabs.
Would you please suggest any solution?
I try to post this on the sample code provide git, but they cannot post the bug in git.
here is sample code URL [https://github.com/microsoft/PowerBI-Developer-Samples](url)

Error Details:
**One or more errors occurred. (AADSTS50196: The server terminated an operation because it encountered a client request loop.** Please contact your app vendor.
Trace ID: 62b0fef7-1b1e-4196-9b67-ce75c55b1d01
Correlation ID: b0d0bf6d-7c22-42d0-8721-8f6d2afd5828
Timestamp: 2021-06-11 12:42:39Z)

at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
at AppOwnsData.Services.AadService.GetAccessToken() in C:\Users\satish.rabari\Source\Repos\PowerBI-Developer-Samples\.NET Core\Embed for your customers\AppOwnsData\Services\AadService.cs:line 48
at AppOwnsData.Services.PbiEmbedService.GetPowerBIClient() in C:\Users\satish.rabari\Source\Repos\PowerBI-Developer-Samples\.NET Core\Embed for your customers\AppOwnsData\Services\PbiEmbedService.cs:line 33
at AppOwnsData.Services.PbiEmbedService.GetEmbedToken(Guid reportId, IList`1 datasetIds, Guid targetWorkspaceId) in C:\Users\satish.rabari\Source\Repos\PowerBI-Developer-Samples\.NET Core\Embed for your customers\AppOwnsData\Services\PbiEmbedService.cs:line 153
at AppOwnsData.Services.PbiEmbedService.GetEmbedParams(Guid workspaceId, Guid reportId, Guid additionalDatasetId) in C:\Users\satish.rabari\Source\Repos\PowerBI-Developer-Samples\.NET Core\Embed for your customers\AppOwnsData\Services\PbiEmbedService.cs:line 75
at AppOwnsData.Controllers.EmbedInfoController.GetEmbedInfo() in C:\Users\satish.rabari\Source\Repos\PowerBI-Developer-Samples\.NET Core\Embed for your customers\AppOwnsData\Controllers\EmbedInfoController.cs:line 45

**Comment by paulinbar** [comment]
Thanks for your comment, @satishrabari. This looks like a support request rather than documentation feedback. For support with the developer samples on Github, please try our [support page](https://support.powerbi.com). You might also get some help in the [Power BI Community]( https://community.powerbi.com).
