### ISSUE TITLE
DM_GWPipeline_Gateway_ServerUnreachable

### ISSUE THREAD

**Issue by cveld** [MicrosoftDocs/powerbi-docs#4606]
We have issues with our setup (vnet gateway) and get the following error message regularly when the data volume is high (10 GB+):

```
Finished executing instance 'Margin Analysis' Execution Package 'Margin Analysis SSL'
Execution failed
Start Time : 5/24/2023 6:30:07 AM End Time : 5/24/2023 11:48:26 AM on server: vm-timextender-
-Execute Execution Package Margin Analysis SSL 'Processing failed'
    Microsoft.AnalysisServices.OperationException: Failed to save modifications to the server. Error returned: '{"error":{"code":"DM_GWPipeline_Gateway_ServerUnreachable","pbi.error":{"code":"DM_GWPipeline_Gateway_ServerUnreachable","parameters":{},"details":[{"code":"DM_ErrorDetailNameCode_UnderlyingErrorCode","detail":{"type":1,"value":"-2146232060"}},{"code":"DM_ErrorDetailNameCode_UnderlyingErrorMessage","detail":{"type":1,"value":"<pi>A transport-level error has occurred when receiving results from the server. (provider: Session Provider, error: 19 - Physical connection is not usable)</pi>"}},{"code":"DM_ErrorDetailNameCode_UnderlyingHResult","detail":{"type":1,"value":"-2146232060"}},{"code":"DM_ErrorDetailNameCode_UnderlyingNativeErrorCode","detail":{"type":1,"value":"-1"}}],"exceptionCulprit":1}}}

    Technical Details:
    RootActivityId: a210e836-a245-475e-a118-0ccd89494326
    Date (UTC): 5/24/2023 9:47:30 AM
    '.
       at Microsoft.AnalysisServices.Tabular.Model.SaveChangesImpl(SaveOptions options)
       at Microsoft.AnalysisServices.Tabular.Database.OnAfterUpdate(UpdateOptions options)
       at TimeXtender.Tabular.Engine.TabularEngine.Process(Model model)

    Details:

    Microsoft.AnalysisServices.OperationException: Failed to save modifications to the server. Error returned: '{"error":{"code":"DM_GWPipeline_Gateway_ServerUnreachable","pbi.error":{"code":"DM_GWPipeline_Gateway_ServerUnreachable","parameters":{},"d...

    System.Exception

Execute PowerBIPremiumEndpoint endpoint PowerBI Margin Analysis:Error:Processing failed
  -Execute PowerBIPremiumEndpoint endpoint PowerBI Margin Analysis 'Processing failed'
      Microsoft.AnalysisServices.OperationException: Failed to save modifications to the server. Error returned: '{"error":{"code":"DM_GWPipeline_Gateway_ServerUnreachable","pbi.error":{"code":"DM_GWPipeline_Gateway_ServerUnreachable","parameters":{},"details":[{"code":"DM_ErrorDetailNameCode_UnderlyingErrorCode","detail":{"type":1,"value":"-2146232060"}},{"code":"DM_ErrorDetailNameCode_UnderlyingErrorMessage","detail":{"type":1,"value":"<pi>A transport-level error has occurred when receiving results from the server. (provider: Session Provider, error: 19 - Physical connection is not usable)</pi>"}},{"code":"DM_ErrorDetailNameCode_UnderlyingHResult","detail":{"type":1,"value":"-2146232060"}},{"code":"DM_ErrorDetailNameCode_UnderlyingNativeErrorCode","detail":{"type":1,"value":"-1"}}],"exceptionCulprit":1}}}

      Technical Details:
      RootActivityId: a210e836-a245-475e-a118-0ccd89494326
      Date (UTC): 5/24/2023 9:47:30 AM
      '.
         at Microsoft.AnalysisServices.Tabular.Model.SaveChangesImpl(SaveOptions options)
         at Microsoft.AnalysisServices.Tabular.Database.OnAfterUpdate(UpdateOptions options)
         at TimeXtender.Tabular.Engine.TabularEngine.Process(Model model)

      Details:

      Microsoft.AnalysisServices.OperationException: Failed to save modifications to the server. Error returned: '{"error":{"code":"DM_GWPipeline_Gateway_ServerUnreachable","pbi.error":{"code":"DM_GWPipeline_Gateway_ServerUnreachable","parameters":{},"d...

      System.Exception
```

 Can you add guidance to the docs how we can resolve this?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 92f41ca5-f249-e0a8-fb68-d19215f5ca66
* Version Independent ID: 74828e70-9e56-afd3-aa11-5bfaab20e384
* Content: [Troubleshoot gateways - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/service-gateway-onprem-tshoot)
* Content Source: [powerbi-docs/connect-data/service-gateway-onprem-tshoot.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-gateway-onprem-tshoot.md)
* Service: **powerbi**
* Sub-service: **powerbi-gateways**
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by davidiseminger** [comment]
Thanks for posting – note that we can only answer feedback related to the documentation, and can’t provide direct support or respond to feature requests.

Your best venue for getting an answer or feedback on your question is from the community (https://community.powerbi.com) or from support at https://support.powerbi.com. You can also provide feedback using the Give Product Feedback button at the bottom of the article page.
